[package]
name = "php-hardened-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
heck = "0.5"

# Обязательно включаем нужные фичи syn:
syn = { version = "2.0", features = ["full", "parsing"] }
